---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - platform.komp.kzyn.dev
  resources:
  - kompservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - platform.komp.kzyn.dev
  resources:
  - kompservices/finalizers
  verbs:
  - update
- apiGroups:
  - platform.komp.kzyn.dev
  resources:
  - kompservices/status
  verbs:
  - get
  - patch
  - update
